### ISSUE TITLE
Biome spawns beyond borders of polluted areas

### ISSUE THREAD

**Issue by SkyJamJar** [O21-Outland/Outland-Toxic-Forest#1]
Description:
Biome spawns beyond borders of polluted areas. No errors shown.

To Reproduce:
Generate a new map.

Expected Behaviour
All biome is clean and non-toxic.

Screenshots

<img width="2381" height="1150" alt="Image" src="https://github.com/user-attachments/assets/ad251d76-aae2-48c3-9aba-0cbff37919c5" />

<img width="2558" height="1536" alt="Image" src="https://github.com/user-attachments/assets/7a9f8e8c-9480-48d4-a9c1-380f385ddbd9" />

HugsLib Log:
Sorry, but HugsLib is broken yet in 1.6.

Additional context
Thank you for your job. I really like this mod and it's my must have in game. I added it first after update

**Comment by neronix17** [comment]
Should be fixed now, thanks.

**Comment by SkyJamJar** [comment]
> Should be fixed now, thanks.

No, still the same 

<img width="1750" height="1312" alt="Image" src="https://github.com/user-attachments/assets/4267bd2c-04e1-413c-a178-14ce83b2e982" />

**Comment by neronix17** [comment]
It is, try unsubbing and reducing to force the mod to redownload, Steam fails with that a lot.

**Comment by SkyJamJar** [comment]
> It is, try unsubbing and reducing to force the mod to redownload, Steam fails with that a lot.

did it, even reloaded steam after unsibscribing. 
But it still persists.  And it's not a mode conflict, I started map only with outland modes active.

<img width="1499" height="1105" alt="Image" src="https://github.com/user-attachments/assets/80f1e6bd-4fc7-4089-b773-5a784bc9b0cc" />

<img width="1313" height="1154" alt="Image" src="https://github.com/user-attachments/assets/c72963b0-1bd1-49c8-b80f-466ae9ff1c41" />

**Comment by neronix17** [comment]
Loaded it up to check, and it is indeed broken again, looks like the vanilla code handling pollution offset has changed, I'll have to override that I guess. Reopening the issue till I have the time to unfuck Ludeons work. 

The way it currently works is that pollution offset will only be used if the worlds pollution is set to 0 on world generation, feels like a remarkably stupid choice considering it's biome specific but that's on par for Ludeon.

**Comment by neronix17** [comment]
Hard coded the fix this time, that's what I get for relying on vanilla systems.

**Comment by SkyJamJar** [comment]
> Hard coded the fix this time, that's what I get for relying on vanilla systems.

Thank you, man. You're my hero
